meta_product_name: "The Farmers' eMarket"
meta_title: "The Farmers' eMarket - Order local and fresh ingredients for your restaurant"
meta_description: "Relevant description"
meta_image: "farm.jpeg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
